### ISSUE TITLE
Database should be encrypted using user's key or password

### ISSUE THREAD

**Issue by samdark** [jepster/yiipass#5]

**Comment by jepster** [comment]
Now you can specify an encryption-secret in config/params.php. There're only hashes in password db-table now. Closing this issue.

**Comment by samdark** [comment]
Nope. That's not the way to go. Service has all the users passwords so if hacked somehow, all the passwords are exposed. Instead it should encrypt per user using user entered password so even if one got the database file he won't be able to decrypt it.

**Comment by jepster** [comment]
How about having a "team secret" for password decryption? It would be saved into the users cookie for usability (no need for entering every session) and de-crypted via a random salt (application config). The team-secret would be validated against an 1-way hash (also in application config).

**Comment by samdark** [comment]
Shared password or key is OK if you want multiple people to access the same storage. Are you going to support only one team per the whole app?

Salt stored in app config doesn't make sense to me. Trying to encrypt the channel by using your own thing isn't really a good idea. Better to use HTTPS.

**Comment by samdark** [comment]
Cookie is probably OK (optionally) but storing password at the server side for the purpose of its validation isn't.

**Comment by samdark** [comment]
Encrypt data using https://github.com/yiisoft/yii2/blob/master/framework/base/Security.php#L18 and when user supplies password or key, try to decrypt it with it. If it doesn't work that means password or key isn't correct.

**Comment by jepster** [comment]
Multi-team functionality is very interessting. I haven't thought about it, but I'll put into my project backlog. I'm going to replace the current encryption- and decryption-methods by the ones from the Yii security component. 

I'll save the "team secret" (can be plain text like "hello world" - depends on that what the team is inserting) in the cookie. So every password will be decrypted via the team secret from cookie on every password request from user.

Along with https and VPN the functionality should be pretty secure. Well, if someone knows how the system works and gets into the user's browser to grab the cookie, the passwords can be stolen. But if the computer is turned on, there's always a risk. 

What do you think about my approach?

**Comment by samdark** [comment]
Sounds OK.

**Comment by jepster** [comment]
Implemented team secret now. So after admin logs in the first time, he's asked for the team secret. With this secret all passwords will be encrypted. The team secret is saved in the browser cookie. Please take a look.
